### ISSUE TITLE
roomType isnt set correctly.

### ISSUE THREAD

**Issue by hyperliskdev** [Java-prog-class-2019/TextAdv2#5]
When a room is called, it is supposed to generated a room type that will say weather it is a great hall, kitchen or the backyard. The number isn't set correctly leaving with the descriptor to say "You find yourself in a nasty drab section of the null."

The null is because the room type doesnt meet any of the if statement requirements.

**Comment by jeremy-bryce** [comment]
I fixed this in Rooms and will commit shortly
